// Generated by tools/generate_mc_data.py.
pub const PLAINS_BIOME: i32 = 40;
pub const ITEM_COUNT: i32 = 1396;
pub const COMPONENT_COUNT: i32 = 96;
pub const PLAYER_ENTITY: i32 = 148;
pub const TAGS: &[u8] = include_bytes!("../../../mc_data/1.21.5/tags.bin");
pub const REGISTRIES: &[u8] = include_bytes!("../../../mc_data/1.21.5/registries.bin");
