services:
  mchprs:
    build:
      # Cargo/target caches live in the prod server's BuildKit builder.
      context: .
      dockerfile: docker/Dockerfile-plot-scale-5
    ports:
      - 25562:25565
    volumes:
      - /srv/mchprs/data:/data
      - /home/minecraft/redstonefun_server/plugins/WorldEdit/schematics:/data/schems/rf:ro
