bind_address = "0.0.0.0:25565"
motd = "§4§lmroww.redstoneFUN.pl §r§71.21.5\n§cMinecraft Redstone o Wysokiej Wydajności"
chat_format = "<{username}> {message}"
max_players = 100
view_distance = 8
neighbor_update_interval_ms = 2000
bungeecord = false
whitelist = false
schemati = false
block_in_hitbox = true
auto_redpiler = true
default_tps = 20
fast_render_threshold = 200
fast_render_send_rate = 10
rhistory_memory_limit_mib = 2048
rhistory_work_memory_limit_mib = 256

[velocity]
secret_file = "/run/velocity/forwarding.secret"
