FROM rust:slim

RUN apt-get update \
    && apt-get install -y \
    git pkg-config libssl-dev

COPY ./ ./
RUN sed -i 's/pub const PLOT_SCALE: u32 = 4/pub const PLOT_SCALE: u32 = 5/g' crates/core/src/plot/mod.rs

RUN cargo build --release

VOLUME ["/data"]
WORKDIR /data

CMD ["/target/release/mchprs"]