# Allow only compilation inputs, including generated assets when present.
**
!Cargo.toml
!Cargo.lock
!docker/
!docker/Config.toml
!build.rs
!src/
!src/**
!crates/
!crates/**
!mc_data/
!mc_data/**
!.cargo/
!.cargo/config
!.cargo/config.toml
**/target/
