<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent><groupId>pl.redstonefun</groupId><artifactId>network-chat</artifactId><version>1.0.0</version></parent>
  <artifactId>chat-velocity</artifactId>
  <dependencies>
    <dependency><groupId>com.velocitypowered</groupId><artifactId>velocity-api</artifactId><version>${velocity.version}</version><scope>provided</scope></dependency>
    <dependency><groupId>net.luckperms</groupId><artifactId>api</artifactId><version>5.4</version><scope>provided</scope></dependency>
  </dependencies>
  <build><finalName>redstonefun-chat-velocity</finalName></build>
</project>
