"""Rebuild target data from checked-in, pinned minecraft-data inputs. Python 3."""
import itertools
import json
import pathlib
import struct

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "mc_data/1.21.5"

def load(name):
    return json.loads((DATA / (name + ".json")).read_text())

def states(blocks):
    result = []
    for block in blocks:
        axes = [s.get("values", ["true", "false"] if s["type"] == "bool" else [str(i) for i in range(s["num_values"])]) for s in block["states"]]
        for offset, values in enumerate(itertools.product(*axes)):
            result.append((block["minStateId"] + offset, block["name"], tuple(zip([s["name"] for s in block["states"]], values))))
    return result

old, new = states(load("legacy_blocks")), states(load("blocks"))
index = {(name, props): i for i, name, props in new}
old_index = {(name, props): i for i, name, props in old}
# Vanilla renamed grass to short_grass; other property additions use target defaults.
new_blocks = {b["name"]: b for b in load("blocks")}
new_states = {i: (name, props) for i, name, props in new}
mapping = []
for i, name, props in old:
    name = "short_grass" if name == "grass" else name
    defaults = dict(new_states[new_blocks[name]["defaultState"]][1])
    defaults.update(dict(props))
    target = index.get((name, tuple((k, defaults[k]) for k,_ in new_states[new_blocks[name]["defaultState"]][1])))
    if target is None:
        raise ValueError((i, name, props))
    mapping.append(target)
reverse = [4294967295] * len(new)
for i, target in enumerate(mapping):
    reverse[target] = i

def array(name, values, value_type="u32"):
    return "#[rustfmt::skip]\npub static " + name + ": &[" + value_type + "] = &[\n" + "\n".join("    " + ",".join(map(str, values[i:i+32])) + "," for i in range(0, len(values), 32)) + "\n];\n"

text = "// Generated by tools/generate_mc_data.py. Do not edit.\n"
text += array("LEGACY_BLOCK_STATES", mapping) + array("TARGET_TO_LEGACY", reverse)
state_blocks = [index for index, block in enumerate(load("blocks"))
                for _ in range(block["minStateId"], block["maxStateId"] + 1)]
assert len(state_blocks) == len(new) and max(state_blocks) <= 65535
text += array("STATE_TO_BLOCK_INDEX", state_blocks, "u16")
# Slab classification is resolved here, never by name in the simulation loop.
# Codes: 0 = other block, 1 = top, 2 = bottom, 3 = double.
slab_codes = {"top": 1, "bottom": 2, "double": 3}
slab_types = [
    slab_codes[dict(properties)["type"]] if name.endswith("_slab") else 0
    for _, name, properties in new
]
text += array("STATE_SLAB_TYPES", slab_types, "u8")
text += "#[rustfmt::skip]\npub static BLOCKS: &[(&str,u32,u32,u32,u32)] = &[\n" + "\n".join(f'    ("{b["name"]}",{b["id"]},{b["minStateId"]},{b["maxStateId"]},{b["defaultState"]}),' for b in load("blocks")) + "\n];\n"
text += "#[rustfmt::skip]\npub static STATE_PROPERTIES: &[&[(&str,&str)]] = &[\n" + "\n".join("    &[" + ",".join(f'(\"{k}\",\"{v}\")' for k,v in props) + "]," for _,_,props in new) + "\n];\n"
old_items = load("legacy_items")
target_items = {i["name"]: i["id"] for i in load("items")}
legacy_items = [target_items["air"]] * (max(i["id"] for i in old_items) + 1)
for i in old_items:
    legacy_items[i["id"]] = target_items[{"grass":"short_grass", "scute":"turtle_scute"}.get(i["name"], i["name"])]
text += array("LEGACY_ITEMS", legacy_items)
reverse_items = [4294967295] * len(target_items)
for i in old_items:
    reverse_items[target_items[{"grass":"short_grass", "scute":"turtle_scute"}.get(i["name"], i["name"])]] = i["id"]
text += array("TARGET_TO_LEGACY_ITEMS", reverse_items)
text += "#[rustfmt::skip]\npub static ITEMS: &[(&str,u32)] = &[\n" + "\n".join(f'    ("{i["name"]}",{i["stackSize"]}),' for i in load("items")) + "\n];\n"
def vi(i):
    out = bytearray()
    while i > 127:
        out.append((i & 127) | 128); i >>= 7
    out.append(i)
    return bytes(out)

def string(s):
    b = s.encode(); return vi(len(b)) + b

tags = {"byte": 1, "short": 2, "int": 3, "long": 4, "float": 5, "double": 6, "byteArray": 7, "string": 8, "list": 9, "compound": 10, "intArray": 11, "longArray": 12}
def payload(tag):
    t, v = tag["type"], tag["value"]
    if t == "compound":
        return b"".join(bytes([tags[x["type"]]]) + struct.pack(">H", len(k.encode())) + k.encode() + payload(x) for k, x in v.items()) + b"\0"
    if t == "string":
        return struct.pack(">H", len(v.encode())) + v.encode()
    if t == "list":
        return bytes([tags[v["type"]]]) + struct.pack(">i", len(v["value"])) + b"".join(payload({"type":v["type"], "value":x}) for x in v["value"])
    if t == "long":
        if isinstance(v, list): v = (v[0] << 32) | (v[1] & 0xffffffff)
        return struct.pack(">Q", v & 0xffffffffffffffff)
    if t.endswith("Array"):
        inner = {"byteArray":"byte", "intArray":"int", "longArray":"long"}[t]
        return struct.pack(">i", len(v)) + b"".join(payload({"type":inner,"value":x}) for x in v)
    return struct.pack(">" + {"byte":"b", "short":"h", "int":"i", "float":"f", "double":"d"}[t], v)

def typed(value):
    if isinstance(value,bool):return {"type":"byte","value":int(value)}
    if isinstance(value,int):return {"type":"int","value":value}
    if isinstance(value,float):return {"type":"double","value":value}
    if isinstance(value,str):return {"type":"string","value":value}
    if isinstance(value,list):
        values=[typed(v) for v in value]
        kind=values[0]["type"] if values else "compound"
        if any(v["type"]!=kind for v in values):raise ValueError("mixed NBT registry list")
        return {"type":"list","value":{"type":kind,"value":[v["value"] for v in values]}}
    return {"type":"compound","value":{k:typed(v) for k,v in value.items()}}
registries={name:{"entries":[{"key":"minecraft:"+key,"value":typed(value)} for key,value in entries.items()]} for name,entries in load("registry_data").items()}
# Preserve the baseline geometry and bright redstone-building environment.
dimension = next(e["value"] for e in registries["minecraft:dimension_type"]["entries"] if e["key"]=="minecraft:overworld")
dimension["value"].update({"min_y":{"type":"int","value":0}, "height":{"type":"int","value":256}, "logical_height":{"type":"int","value":256}, "ambient_light":{"type":"float","value":1.0}, "fixed_time":{"type":"long","value":6000}})
registries["minecraft:dimension_type"]["entries"] = [{"key":"mchprs:dimension", "value":dimension}]
plains_id = next(i for i,e in enumerate(registries["minecraft:worldgen/biome"]["entries"]) if e["key"] == "minecraft:plains")
out = bytearray()
for name, registry in registries.items():
    packet = vi(7) + string(name) + vi(len(registry["entries"]))
    for entry in registry["entries"]:
        packet += string(entry["key"]) + b"\1" + bytes([10]) + payload(entry["value"])
    out += struct.pack(">I", len(packet)) + packet
(DATA / "registries.bin").write_bytes(out)
tag_data = load("registry_tags")
tag_packet = vi(len(tag_data))
for registry, registry_tags in tag_data.items():
    tag_packet += string(registry) + vi(len(registry_tags))
    for name, entries in registry_tags.items():
        tag_packet += string(name) + vi(len(entries)) + b"".join(vi(i) for i in entries)
(DATA / "tags.bin").write_bytes(tag_packet)
ids=load("builtin_ids")
text += "#[rustfmt::skip]\npub mod block_entity_types {\n"+"\n".join(f'pub const {key.split(":")[1].upper()}: i32 = {value["protocol_id"]};' for key,value in ids["minecraft:block_entity_type"]["entries"].items())+"\n}\n"
(ROOT / "crates/blocks/src/generated.rs").write_text(text)
(ROOT / "crates/network/src/generated.rs").write_text(f'// Generated by tools/generate_mc_data.py.\npub const PLAINS_BIOME: i32 = {plains_id};\npub const ITEM_COUNT: i32 = {len(load("items"))};\npub const COMPONENT_COUNT: i32 = {len(ids["minecraft:data_component_type"]["entries"])};\npub const PLAYER_ENTITY: i32 = {ids["minecraft:entity_type"]["entries"]["minecraft:player"]["protocol_id"]};\npub const TAGS: &[u8] = include_bytes!("../../../mc_data/1.21.5/tags.bin");\npub const REGISTRIES: &[u8] = include_bytes!("../../../mc_data/1.21.5/registries.bin");\n')
print(f"Generated {len(mapping)} legacy state mappings, {len(new)} target states, {len(registries)} registries; plains={plains_id}")
